### PR TITLE
Add title element to SVG to support alt text

### PR DESCRIPTION
**Pull request by tverlaan**
Thanks for creating this library. Are you open to support adding the title element to the SVG to be able to provide alt text?

### CODE REVIEW

**Comment by treebee** [comment]
Hey @tverlaan, totally. Thanks for the contribution! :)

Just one little thing, can we please add a simple test case for this new addition? Something like:

```elixir
    assert Feathericons.volume(title: "Volume Icon") |> Phoenix.HTML.safe_to_string() =~
             "<title>Volume Icon</title>"
```

**Comment by tverlaan** [comment]
Yes perfect. I also added a refute for when no title is given :-)

**Comment by treebee** [comment]
Perfect, thank you, that was fast :D

I will create a new release right away.

**Comment by treebee** [comment]
A new release is published. Thanks again!

**Comment by tverlaan** [comment]
That's fast as well ;)

Thanks!

**Pull request merged**
